<?php

/**
 * @file
 * Displays reportes on sales, customers, and products to store admin.
 *
 * The reportes module creates a few table-based reportes for an Ubercart store.
 * Store admins can view reportes for sales between different dates, customers
 * by the products purchased and money spent, and products by their views,
 * number sold, and revenue produced.
 */

/**
 * The maximum number of records.
 */
define('REPORTES_MAX_RECORDS', PHP_INT_MAX);


/**
 * Implements hook_menu().
 */
function reportes_menu() {
  global $user;
  $items = array();

  $items['admin/content/inventarios/reportes/getcsv/%/%'] = array(
    'page callback' => 'reportes_get_csv',
    'page arguments' => array(4, 5),
    'access arguments' => array('view reportes'),
    'type' => MENU_CALLBACK,
    'file' => 'reportes.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function reportes_theme() {
  return array(
    'reportes_product_table' => array(
      'variables' => array('header' => NULL, 'rows' => NULL, 'attributes' => array(), 'caption' => NULL, 'colgroups' => array(), 'sticky' => TRUE, 'empty' => ''),
      'file' => 'reportes.admin.inc',
    ),
  );
}

/**
 * Implements hook_init().
 */
function reportes_init() {
  if (arg(0) == 'admin' && arg(1) == 'store' && arg(2) == 'reportes') {
    drupal_add_css(drupal_get_path('module', 'reportes') . '/reportes.css');
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for uc_store_settings_form().
 */
function reportes_form_uc_store_settings_form_alter(&$form, &$form_state) {
  $form['reportes'] = array(
    '#type' => 'fieldset',
    '#title' => t('Report settings'),
    '#group' => 'store',
  );
  $form['reportes']['reportes_table_size'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of rows to show in reportes'),
    '#description' => t('The maximum number of rows displayed on one page for a report table.'),
    '#default_value' => variable_get('reportes_table_size', 30),
    '#size' => 5,
  );

  $options = array();
  foreach (uc_order_status_list() as $status) {
    $options[$status['id']] = $status['title'];
  }

  $form['reportes']['reportes_reported_statuses'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Reported statuses'),
    '#description' => t('Only orders with selected statuses will be included in reportes.'),
    '#options' => $options,
    '#default_value' => variable_get('reportes_reported_statuses', array('completed')),
    '#multiple' => TRUE,
  );
}

/**
 * Returns a SQL friendly array of order statuses for orders used in reportes.
 */
function reportes_order_statuses() {
  $statuses = variable_get('reportes_reported_statuses', array('completed'));

  return $statuses;
}
